# Generated by Django 4.2.1 on 2023-06-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_usuarios_listaanime_usuarios_listamanga'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
