# Generated by Django 4.2.1 on 2023-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manga',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
